version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: daily
    target-branch: "primary"
    open-pull-requests-limit: 99
    groups:
      composer-minor-patch:
        update-types:
          - minor
          - patch
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    groups:
      github-actions:
        patterns:
          - "*"